#!/bin/sh

# This script gets the efi utility 'cert-to-efi-sig-list' from a debian container.
# It is not available in fedora.

set -e

if [ -x ./cert-to-efi-sig-list ]; then
	echo "The cert-to-efi-sig-list executable file already exists."
	echo "To get a newer version delete the file and rerun."
	exit 0
fi

podman pull debian:latest
podman build -t efitools_image -f Dockerfile-get-efitools

podman create --name efitools_instance efitools_image
podman cp efitools_instance:/bin/cert-to-efi-sig-list $(pwd)/
podman rm -f efitools_instance
podman rmi efitools_image

echo "Done!"

