#!/bin/sh

set -e

# sign-binaries - Script to sign UEFI binaries.

# Abort if a db key does not exist.
if [ ! -e keys/db.key ]; then
  echo "Error: keys/db.key not found, aborting!"
  exit 1
fi

if [ "$(id -u)" != "0" ]; then
  echo "Error: Must be root!"
  exit 1
fi

# It is safe to sign the binaries with additional keys.
# It should still boot without enrolling the new keys.

sign_bin() {
  if [ -e $1.save ]; then
    if diff $1 $1.save ; then
      echo "Info: File ${1} does not need to be resigned."
    else
      echo "Info: Resigning ${1}."
      sbsign --key keys/db.key --cert keys/db.crt --output ${1} $1
      cp -p $1 $1.save
    fi
  else
    echo "Info: Signing ${1}."
    sbsign --key keys/db.key --cert keys/db.crt --output ${1} $1
    cp -p $1 $1.save
  fi
}

# Sign the latest kernel.
for i in $(ls -t /boot/vmlinuz*) ; do f=$i ; break ; done
sign_bin $f

sign_bin /boot/efi/EFI/fedora/shimx64.efi
sign_bin /boot/efi/EFI/fedora/mmx64.efi
sign_bin /boot/efi/EFI/fedora/grubx64.efi

echo "Done!"

exit 0

